import React, { useState } from 'react';
import { Alert, Modal, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { APPLICATION_STATUS_OPTIONS } from '../applicationStatuses';
import type { Application } from '../types/domain';
import type { ApplicationContext } from '../services/applicationDetailService';
import { AddApplicationModal } from '../components/AddApplicationModal';
import type { ApplicationFormValues } from '../schemas/applicationSchema';
import { InterviewModal } from '../components/InterviewModal';
import type { InterviewFormValues } from '../schemas/interviewSchema';
import type { Interview } from '../services/interviewService';
import { IconButton, Logo, PrimaryButton, SectionHeader, StatusBadge } from '../components';
import { useTheme } from '../context';
import { radius, spacing, typography } from '../theme';

export function ApplicationDetailScreen({ item, context, onBack, onToast, onUpdate, onCreateInterview, onUpdateInterview, onCompleteInterview, onCancelInterview, onDeleteInterview, onRemindInterview, onAddDocument, onFavorite, onDuplicate, onArchive, onDelete }: { item: Application; context: ApplicationContext; onBack: () => void; onToast: (message: string) => void; onUpdate: (values: ApplicationFormValues) => Promise<boolean>; onCreateInterview: (values: InterviewFormValues) => Promise<boolean>; onUpdateInterview: (id: string, values: InterviewFormValues) => Promise<boolean>; onCompleteInterview: (id: string) => Promise<void>; onCancelInterview: (id: string) => Promise<void>; onDeleteInterview: (id: string) => Promise<void>; onRemindInterview: (interview: Interview) => Promise<void>; onAddDocument: () => Promise<void>; onFavorite: () => Promise<void>; onDuplicate: () => Promise<void>; onArchive: () => Promise<void>; onDelete: () => Promise<void> }) {
  const theme = useTheme();
  const [actionsOpen, setActionsOpen] = useState(false);
  const [confirmDelete, setConfirmDelete] = useState(false);
  const [editing, setEditing] = useState(false);
  const [schedulingInterview, setSchedulingInterview] = useState(false);
  const [editingInterview, setEditingInterview] = useState<Interview | null>(null);
  const timeline = APPLICATION_STATUS_OPTIONS.map(status => status.label);
  const active = timeline.indexOf(item.status);
  const facts: [keyof typeof Ionicons.glyphMap, string, string][] = [['cash-outline', item.salary || 'Not listed', 'SALARY'], ['location-outline', item.location, 'LOCATION'], ['business-outline', item.mode, 'WORK MODE']];
  return (
    <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>
      <View style={styles.nav}><IconButton name="arrow-back" label="Back" onPress={onBack} /><View style={styles.navActions}><IconButton name={item.favorite ? 'heart' : 'heart-outline'} label="Favorite" onPress={onFavorite} /><IconButton name="share-outline" label="Share" onPress={() => onToast('Application link copied')} /><IconButton name="ellipsis-horizontal" label="More options" onPress={() => setActionsOpen(true)} /></View></View>
      <View style={styles.hero}>
        <Logo initials={item.initials} color={item.logoColor} size={64} />
        <View style={styles.heroText}><Text style={[typography.screenTitle, { color: theme.textPrimary }]}>{item.title}</Text><Text style={[typography.body, { color: theme.textSecondary, marginTop: 3 }]}>{item.company} · {item.location}</Text><View style={{ alignSelf: 'flex-start', marginTop: spacing.sm }}><StatusBadge status={item.status} /></View></View>
      </View>
      <View style={[styles.facts, { borderTopColor: theme.border, borderBottomColor: theme.border }]}>
        {facts.map(([icon, value, label]) => <View key={label} style={styles.fact}><Ionicons name={icon} size={19} color={theme.primary} /><Text numberOfLines={1} style={[typography.bodyMedium, { color: theme.textPrimary, marginTop: 7 }]}>{value}</Text><Text style={[typography.caption, { color: theme.textSecondary }]}>{label}</Text></View>)}
      </View>

      <View><SectionHeader title="Application journey" /><View style={styles.timeline}>{timeline.map((step, index) => { const done = index <= active; return <View key={step} style={styles.timelineStep}><View style={styles.timelineRail}><View style={[styles.timelineNode, { backgroundColor: done ? theme.primary : theme.surface, borderColor: done ? theme.primary : theme.border }]}>{done && <Ionicons name="checkmark" size={13} color="#fff" />}</View>{index < timeline.length - 1 && <View style={[styles.timelineLine, { backgroundColor: index < active ? theme.primary : theme.border }]} />}</View><View style={{ flex: 1, paddingBottom: index < timeline.length - 1 ? spacing.lg : 0 }}><Text style={[typography.cardTitle, { color: done ? theme.textPrimary : theme.textSecondary }]}>{step}</Text><Text style={[typography.caption, { color: theme.textSecondary, marginTop: 2 }]}>{index === active ? 'Current stage · Sep 9' : index < active ? `Completed · Sep ${4 + index}` : 'Pending'}</Text></View></View>; })}</View></View>

      <View><SectionHeader title="Interviews" action="Schedule" onAction={() => setSchedulingInterview(true)} />{context.interviews.length ? context.interviews.map(interview => <View key={interview.id} style={[styles.interviewCard, { backgroundColor: interview.status === 'SCHEDULED' ? theme.warningMuted : theme.surface, borderColor: interview.status === 'SCHEDULED' ? (theme.dark ? '#62471D' : '#F8D99D') : theme.border, marginBottom: spacing.xs }]}><View style={[styles.iconBox, { backgroundColor: theme.surface }]}><Ionicons name={interview.status === 'COMPLETED' ? 'checkmark-circle-outline' : interview.status === 'CANCELLED' ? 'close-circle-outline' : 'videocam-outline'} size={22} color={interview.status === 'COMPLETED' ? theme.success : interview.status === 'CANCELLED' ? theme.danger : theme.warning} /></View><Pressable onPress={() => setEditingInterview(interview)} style={{ flex: 1 }}><Text style={[typography.cardTitle, { color: theme.textPrimary }]}>{interview.interview_type}</Text><Text style={[typography.bodyMedium, { color: theme.textSecondary, marginTop: 3 }]}>{new Date(interview.scheduled_at).toLocaleString()} · {interview.duration_minutes} min</Text></Pressable><View style={styles.interviewActions}>{interview.status === 'SCHEDULED' && <><Pressable accessibilityLabel="Set reminder" onPress={() => onRemindInterview(interview)}><Ionicons name="notifications-outline" size={19} color={theme.primary} /></Pressable><Pressable accessibilityLabel="Mark completed" onPress={() => onCompleteInterview(interview.id)}><Ionicons name="checkmark-circle-outline" size={20} color={theme.success} /></Pressable><Pressable accessibilityLabel="Cancel interview" onPress={() => onCancelInterview(interview.id)}><Ionicons name="close-circle-outline" size={20} color={theme.warning} /></Pressable></>}<Pressable accessibilityLabel="Delete interview" onPress={() => Alert.alert('Delete interview?', 'This action cannot be undone.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete', style: 'destructive', onPress: () => onDeleteInterview(interview.id) }])}><Ionicons name="trash-outline" size={19} color={theme.danger} /></Pressable></View></View>) : item.status === 'Interview' ? <View style={[styles.interviewCard, { backgroundColor: theme.warningMuted, borderColor: theme.dark ? '#62471D' : '#F8D99D' }]}><View style={[styles.iconBox, { backgroundColor: theme.surface }]}><Ionicons name="videocam-outline" size={22} color={theme.warning} /></View><View style={{ flex: 1 }}><Text style={[typography.cardTitle, { color: theme.textPrimary }]}>Portfolio conversation</Text><Text style={[typography.bodyMedium, { color: theme.textSecondary, marginTop: 3 }]}>Demo interview · 45 min</Text></View><Pressable onPress={() => onToast('Interview reminder added')}><Text style={[typography.bodyMedium, { color: theme.warning }]}>Remind me</Text></Pressable></View> : <Text style={[typography.body, { color: theme.textSecondary }]}>No interviews scheduled for this application.</Text>}</View>

      <View><SectionHeader title="Recruiter" /><View style={styles.recruiter}><View style={[styles.avatar, { backgroundColor: theme.primaryMuted }]}><Text style={[styles.avatarText, { color: theme.primary }]}>{item.recruiterName?.split(' ').map(part => part[0]).join('').slice(0, 2).toUpperCase() || '—'}</Text></View><View style={{ flex: 1 }}><Text style={[typography.cardTitle, { color: theme.textPrimary }]}>{item.recruiterName || 'No recruiter added'}</Text><Text style={[typography.bodyMedium, { color: theme.textSecondary }]}>{item.recruiterEmail || 'Add contact details for quick follow-up'}</Text></View>{item.recruiterEmail && <IconButton name="mail-outline" label="Email recruiter" onPress={() => onToast('Opening email')} />}</View></View>
      <View><SectionHeader title="Notes" action="Edit" /><Text style={[typography.body, { color: theme.textSecondary }]}>{item.notes || 'No notes yet. Add interview context, follow-up details, or your next action.'}</Text></View>
      <View><SectionHeader title="Documents" action="Add" onAction={onAddDocument} />{context.documents.length ? context.documents.map(document => <View key={document.id} style={[styles.document, { borderColor: theme.border, marginBottom: spacing.xs }]}><View style={[styles.iconBox, { backgroundColor: theme.primaryMuted }]}><Ionicons name="document-text-outline" size={21} color={theme.primary} /></View><View style={{ flex: 1 }}><Text style={[typography.bodyMedium, { color: theme.textPrimary }]}>{document.name}</Text><Text style={[typography.caption, { color: theme.textSecondary }]}>{document.document_type.replace('_', ' ')} · {document.size_bytes ? `${Math.round(document.size_bytes / 1024)} KB` : 'Private file'}</Text></View><Ionicons name="download-outline" size={20} color={theme.textSecondary} /></View>) : <Text style={[typography.body, { color: theme.textSecondary }]}>No documents attached to this application.</Text>}</View>
      {context.activity.length > 0 && <View><SectionHeader title="Activity" />{context.activity.slice(0, 6).map(activity => <View key={activity.id} style={styles.activityRow}><View style={[styles.activityDot, { backgroundColor: theme.primary }]} /><View><Text style={[typography.bodyMedium, { color: theme.textPrimary }]}>{activity.title}</Text><Text style={[typography.caption, { color: theme.textSecondary }]}>{new Date(activity.created_at).toLocaleString()}</Text></View></View>)}</View>}
      <PrimaryButton title="Update application" icon="create-outline" onPress={() => setEditing(true)} />
      <AddApplicationModal visible={editing} title="Update application" initialValues={{ companyName: item.company, jobTitle: item.title, location: item.location === 'Location not set' ? '' : item.location, jobUrl: item.jobUrl || '', workMode: item.mode === 'On-site' ? 'ONSITE' : item.mode === 'Hybrid' ? 'HYBRID' : 'REMOTE', status: item.rawStatus, priority: item.priority.toUpperCase() as 'LOW' | 'MEDIUM' | 'HIGH', source: item.source || '', salaryMin: '', salaryMax: '', currency: 'USD', notes: item.notes || '' }} onClose={() => setEditing(false)} onSave={async values => { const saved = await onUpdate(values); onToast(saved ? 'Application updated' : 'Application could not be updated'); return saved; }} />
      <InterviewModal visible={schedulingInterview || Boolean(editingInterview)} applicationId={item.id} initialValues={editingInterview ? { applicationId: item.id, interviewType: editingInterview.interview_type as InterviewFormValues['interviewType'], scheduledAt: editingInterview.scheduled_at, durationMinutes: editingInterview.duration_minutes, interviewerName: editingInterview.interviewer_name || '', interviewerEmail: editingInterview.interviewer_email || '', meetingLink: editingInterview.meeting_link || '', location: editingInterview.location || '', notes: editingInterview.notes || '' } : undefined} onClose={() => { setSchedulingInterview(false); setEditingInterview(null); }} onSave={values => editingInterview ? onUpdateInterview(editingInterview.id, values) : onCreateInterview(values)} />
      <Modal visible={actionsOpen} transparent animationType="fade" onRequestClose={() => setActionsOpen(false)}><View style={styles.modalRoot}><Pressable style={[StyleSheet.absoluteFill, { backgroundColor: theme.overlay }]} onPress={() => setActionsOpen(false)} /><View style={[styles.actionSheet, { backgroundColor: theme.surface }]}><View style={[styles.actionHandle, { backgroundColor: theme.border }]} /><Text style={[typography.sectionTitle, { color: theme.textPrimary }]}>{confirmDelete ? 'Delete application?' : 'Manage application'}</Text>{confirmDelete ? <><Text style={[typography.body, { color: theme.textSecondary }]}>This action cannot be undone. All related interviews, notes and activity will also be deleted.</Text><View style={styles.confirmRow}><Pressable onPress={() => setConfirmDelete(false)} style={[styles.actionButton, { borderColor: theme.border }]}><Text style={[typography.bodyMedium, { color: theme.textPrimary }]}>Cancel</Text></Pressable><Pressable onPress={async () => { setActionsOpen(false); await onDelete(); }} style={[styles.actionButton, { backgroundColor: theme.danger, borderColor: theme.danger }]}><Text style={[typography.bodyMedium, { color: '#fff' }]}>Delete</Text></Pressable></View></> : <View>{[['copy-outline', 'Duplicate application', onDuplicate], ['archive-outline', 'Archive application', onArchive]].map(([icon, label, action]) => <Pressable key={label as string} onPress={async () => { setActionsOpen(false); await (action as () => Promise<void>)(); }} style={[styles.actionRow, { borderBottomColor: theme.border }]}><Ionicons name={icon as keyof typeof Ionicons.glyphMap} size={21} color={theme.textPrimary} /><Text style={[typography.bodyMedium, { color: theme.textPrimary, flex: 1 }]}>{label as string}</Text><Ionicons name="chevron-forward" size={18} color={theme.textSecondary} /></Pressable>)}<Pressable onPress={() => setConfirmDelete(true)} style={styles.actionRow}><Ionicons name="trash-outline" size={21} color={theme.danger} /><Text style={[typography.bodyMedium, { color: theme.danger }]}>Delete application</Text></Pressable></View>}</View></View></Modal>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  content: { paddingHorizontal: spacing.lg, paddingTop: spacing.md, paddingBottom: spacing.huge, gap: spacing.xxl },
  nav: { flexDirection: 'row', justifyContent: 'space-between' }, navActions: { flexDirection: 'row', gap: spacing.xs },
  hero: { flexDirection: 'row', gap: spacing.md, alignItems: 'flex-start' }, heroText: { flex: 1 },
  facts: { flexDirection: 'row', borderTopWidth: 1, borderBottomWidth: 1, paddingVertical: spacing.lg }, fact: { flex: 1, alignItems: 'center', paddingHorizontal: spacing.xs },
  timeline: { paddingHorizontal: spacing.xs }, timelineStep: { flexDirection: 'row', gap: spacing.sm }, timelineRail: { width: 22, alignItems: 'center' },
  timelineNode: { width: 22, height: 22, borderRadius: 11, borderWidth: 2, alignItems: 'center', justifyContent: 'center' }, timelineLine: { width: 2, flex: 1, minHeight: 35 },
  interviewCard: { flexDirection: 'row', gap: spacing.sm, alignItems: 'center', borderRadius: radius.lg, borderWidth: 1, padding: spacing.md },
  interviewActions: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  iconBox: { width: 44, height: 44, borderRadius: radius.md, alignItems: 'center', justifyContent: 'center' },
  recruiter: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, avatar: { width: 48, height: 48, borderRadius: 24, alignItems: 'center', justifyContent: 'center' }, avatarText: { fontSize: 15, fontWeight: '700' },
  document: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, borderWidth: 1, borderRadius: radius.md, padding: spacing.sm },
  activityRow: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.sm, marginBottom: spacing.md }, activityDot: { width: 8, height: 8, borderRadius: 4, marginTop: 6 },
  modalRoot: { flex: 1, justifyContent: 'flex-end' }, actionSheet: { borderTopLeftRadius: radius.xl, borderTopRightRadius: radius.xl, padding: spacing.lg, paddingBottom: spacing.xxxl, gap: spacing.md }, actionHandle: { width: 40, height: 4, borderRadius: 2, alignSelf: 'center', marginBottom: spacing.xs }, actionRow: { minHeight: 56, flexDirection: 'row', alignItems: 'center', gap: spacing.sm, borderBottomWidth: 1 }, confirmRow: { flexDirection: 'row', gap: spacing.sm }, actionButton: { flex: 1, height: 48, borderRadius: radius.md, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
});
