import React, { useState } from 'react';
import { Controller, useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { Ionicons } from '@expo/vector-icons';
import { KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { z } from 'zod';
import { Field, PrimaryButton } from '../../components';
import { useTheme } from '../../context';
import { friendlyError } from '../../lib/errors';
import { isDemoModeAvailable, isSupabaseConfigured } from '../../lib/supabase';
import { forgotPasswordSchema, resetPasswordSchema, signInSchema, signUpSchema, type SignInValues, type SignUpValues } from '../../schemas/authSchemas';
import { sendPasswordReset } from '../../services/authService';
import { useAuthStore } from '../../stores/authStore';
import { radius, spacing, typography } from '../../theme';

type AuthPage = 'welcome' | 'signin' | 'signup' | 'forgot';

export function AuthFlow() {
  const status = useAuthStore(state => state.status);
  const [page, setPage] = useState<AuthPage>('welcome');
  if (status === 'verification') return <VerificationScreen onBack={() => { useAuthStore.setState({ status: 'signedOut', error: null }); setPage('signin'); }} />;
  if (status === 'passwordRecovery') return <KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={{ flex: 1 }}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{ flexGrow: 1 }}><ResetPasswordScreen /></ScrollView></KeyboardAvoidingView>;
  if (page === 'signin') return <SignInScreen onBack={() => setPage('welcome')} onSignUp={() => setPage('signup')} onForgot={() => setPage('forgot')} />;
  if (page === 'signup') return <SignUpScreen onBack={() => setPage('welcome')} onSignIn={() => setPage('signin')} />;
  if (page === 'forgot') return <ForgotPasswordScreen onBack={() => setPage('signin')} />;
  return <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{ flexGrow: 1 }}><WelcomeScreen onSignIn={() => setPage('signin')} onSignUp={() => setPage('signup')} /></ScrollView>;
}

function Brand() {
  const theme = useTheme();
  return <View style={styles.brand}><View style={[styles.brandMark, { backgroundColor: theme.primary }]}><View style={styles.brandLine} /><View style={[styles.brandLine, { width: 14 }]} /><View style={[styles.brandLine, { width: 9 }]} /></View><Text style={[styles.brandName, { color: theme.textPrimary }]}>JobTrack</Text></View>;
}

function WelcomeScreen({ onSignIn, onSignUp }: { onSignIn: () => void; onSignUp: () => void }) {
  const theme = useTheme();
  const enterDemo = useAuthStore(state => state.enterDemo);
  const serverError = useAuthStore(state => state.error);
  return <View style={styles.welcome}><Brand /><View style={[styles.heroVisual, { backgroundColor: theme.surface, borderColor: theme.border }]}><View style={[styles.heroTop, { backgroundColor: theme.textPrimary }]}><View style={[styles.heroPill, { backgroundColor: theme.primary }]}><Ionicons name="trending-up" size={16} color="#fff" /></View><View><Text style={[typography.caption, { color: theme.dark ? '#9CA3AF' : '#C2C5CD' }]}>CAREER MOMENTUM</Text><Text style={[styles.heroNumber, { color: theme.background }]}>+24%</Text></View></View><View style={styles.heroBars}>{[38, 55, 46, 78, 62, 92].map((height, index) => <View key={index} style={[styles.heroBar, { height, backgroundColor: index === 5 ? theme.primary : theme.primaryMuted }]} />)}</View><View style={[styles.floatingCard, { backgroundColor: theme.surface, borderColor: theme.border }]}><View style={[styles.floatingIcon, { backgroundColor: theme.successMuted }]}><Ionicons name="checkmark" size={18} color={theme.success} /></View><View><Text style={[typography.bodyMedium, { color: theme.textPrimary }]}>Interview confirmed</Text><Text style={[typography.caption, { color: theme.textSecondary }]}>Linear · Monday at 10:30</Text></View></View></View><View><Text style={[typography.display, { color: theme.textPrimary }]}>Build a job search that moves forward.</Text><Text style={[typography.body, { color: theme.textSecondary, marginTop: spacing.sm }]}>Track every opportunity, prepare with confidence, and understand what gets results.</Text></View><View style={{ gap: spacing.sm }}>{serverError && <ErrorNotice message={serverError} />}<PrimaryButton title="Create your account" onPress={onSignUp} /><Pressable onPress={onSignIn} style={[styles.secondaryButton, { backgroundColor: theme.surface, borderColor: theme.border }]}><Text style={[typography.bodyMedium, { color: theme.textPrimary }]}>I already have an account</Text></Pressable>{isDemoModeAvailable && <Pressable onPress={enterDemo} style={styles.demoButton}><Text style={[typography.bodyMedium, { color: theme.primary }]}>Explore the demo</Text><Ionicons name="arrow-forward" size={16} color={theme.primary} /></Pressable>}</View></View>;
}

function AuthLayout({ title, subtitle, onBack, children }: { title: string; subtitle: string; onBack: () => void; children: React.ReactNode }) {
  const theme = useTheme();
  return <KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={{ flex: 1 }}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.authContent}><Pressable accessibilityLabel="Back" onPress={onBack} style={[styles.back, { borderColor: theme.border, backgroundColor: theme.surface }]}><Ionicons name="arrow-back" size={20} color={theme.textPrimary} /></Pressable><Brand /><View><Text style={[typography.screenTitle, { color: theme.textPrimary }]}>{title}</Text><Text style={[typography.body, { color: theme.textSecondary, marginTop: spacing.xs }]}>{subtitle}</Text></View>{children}</ScrollView></KeyboardAvoidingView>;
}

function SignInScreen({ onBack, onSignUp, onForgot }: { onBack: () => void; onSignUp: () => void; onForgot: () => void }) {
  const theme = useTheme(); const signIn = useAuthStore(state => state.signIn); const busy = useAuthStore(state => state.busy); const serverError = useAuthStore(state => state.error);
  const { control, handleSubmit, formState: { errors } } = useForm<SignInValues>({ resolver: zodResolver(signInSchema), defaultValues: { email: '', password: '' } });
  return <AuthLayout title="Welcome back" subtitle="Sign in to continue building your career momentum." onBack={onBack}><View style={styles.form}><Controller control={control} name="email" render={({ field }) => <Field label="Email" icon="mail-outline" autoCapitalize="none" keyboardType="email-address" value={field.value} onChangeText={field.onChange} onBlur={field.onBlur} placeholder="you@example.com" error={errors.email?.message} />} /><Controller control={control} name="password" render={({ field }) => <Field label="Password" icon="lock-closed-outline" secureTextEntry value={field.value} onChangeText={field.onChange} onBlur={field.onBlur} placeholder="Your password" error={errors.password?.message} />} /><Pressable onPress={onForgot} style={{ alignSelf: 'flex-end' }}><Text style={[typography.bodyMedium, { color: theme.primary }]}>Forgot password?</Text></Pressable>{serverError && <ErrorNotice message={serverError} />}<PrimaryButton title={busy ? 'Signing in…' : 'Sign in'} disabled={busy} onPress={handleSubmit(values => signIn(values))} /></View><FooterPrompt copy="New to JobTrack?" action="Create an account" onPress={onSignUp} /></AuthLayout>;
}

function SignUpScreen({ onBack, onSignIn }: { onBack: () => void; onSignIn: () => void }) {
  const theme = useTheme(); const signUp = useAuthStore(state => state.signUp); const busy = useAuthStore(state => state.busy); const serverError = useAuthStore(state => state.error);
  const { control, handleSubmit, formState: { errors } } = useForm<SignUpValues>({ resolver: zodResolver(signUpSchema), defaultValues: { firstName: '', lastName: '', email: '', password: '' } });
  return <AuthLayout title="Create your account" subtitle="A focused workspace for every step of your job search." onBack={onBack}><View style={styles.form}><View style={styles.nameRow}><View style={{ flex: 1 }}><Controller control={control} name="firstName" render={({ field }) => <Field label="First name" value={field.value} onChangeText={field.onChange} onBlur={field.onBlur} placeholder="Manel" error={errors.firstName?.message} />} /></View><View style={{ flex: 1 }}><Controller control={control} name="lastName" render={({ field }) => <Field label="Last name" value={field.value} onChangeText={field.onChange} onBlur={field.onBlur} placeholder="Benali" error={errors.lastName?.message} />} /></View></View><Controller control={control} name="email" render={({ field }) => <Field label="Email" icon="mail-outline" autoCapitalize="none" keyboardType="email-address" value={field.value} onChangeText={field.onChange} onBlur={field.onBlur} placeholder="you@example.com" error={errors.email?.message} />} /><Controller control={control} name="password" render={({ field }) => <Field label="Password" icon="lock-closed-outline" secureTextEntry value={field.value} onChangeText={field.onChange} onBlur={field.onBlur} placeholder="8+ characters" error={errors.password?.message} />} />{serverError && <ErrorNotice message={serverError} />}<PrimaryButton title={busy ? 'Creating account…' : 'Create account'} disabled={busy} onPress={handleSubmit(values => signUp(values))} /><Text style={[typography.caption, { color: theme.textSecondary, textAlign: 'center' }]}>By continuing, you agree to the Terms and Privacy Policy.</Text></View><FooterPrompt copy="Already have an account?" action="Sign in" onPress={onSignIn} /></AuthLayout>;
}

function ForgotPasswordScreen({ onBack }: { onBack: () => void }) {
  const theme = useTheme(); const [sent, setSent] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const { control, handleSubmit, formState: { errors } } = useForm<z.infer<typeof forgotPasswordSchema>>({ resolver: zodResolver(forgotPasswordSchema), defaultValues: { email: '' } });
  const submit = async ({ email }: { email: string }) => { setBusy(true); setError(''); try { await sendPasswordReset(email); setSent(true); } catch (caught) { setError(friendlyError(caught, 'Unable to send the reset email.')); } finally { setBusy(false); } };
  return <AuthLayout title={sent ? 'Check your inbox' : 'Reset your password'} subtitle={sent ? 'We sent a secure password reset link. It may take a minute to arrive.' : 'Enter your account email and we’ll send a secure reset link.'} onBack={onBack}>{sent ? <View style={[styles.sentIcon, { backgroundColor: theme.successMuted }]}><Ionicons name="mail-open-outline" size={32} color={theme.success} /></View> : <View style={styles.form}><Controller control={control} name="email" render={({ field }) => <Field label="Email" icon="mail-outline" autoCapitalize="none" keyboardType="email-address" value={field.value} onChangeText={field.onChange} placeholder="you@example.com" error={errors.email?.message} />} />{error && <ErrorNotice message={error} />}<PrimaryButton title={busy ? 'Sending…' : 'Send reset link'} disabled={busy || !isSupabaseConfigured} onPress={handleSubmit(submit)} /></View>}</AuthLayout>;
}

function VerificationScreen({ onBack }: { onBack: () => void }) { const theme = useTheme(); return <View style={styles.centered}><View style={[styles.largeIcon, { backgroundColor: theme.primaryMuted }]}><Ionicons name="mail-unread-outline" size={36} color={theme.primary} /></View><Text style={[typography.screenTitle, { color: theme.textPrimary, textAlign: 'center' }]}>Verify your email</Text><Text style={[typography.body, { color: theme.textSecondary, textAlign: 'center', maxWidth: 320 }]}>Open the confirmation link we sent you. JobTrack will continue automatically after verification.</Text><Pressable onPress={onBack}><Text style={[typography.bodyMedium, { color: theme.primary }]}>Back to sign in</Text></Pressable></View>; }

function ResetPasswordScreen() { const theme = useTheme(); const resetPassword = useAuthStore(state => state.resetPassword); const busy = useAuthStore(state => state.busy); const error = useAuthStore(state => state.error); const { control, handleSubmit, formState: { errors } } = useForm<z.infer<typeof resetPasswordSchema>>({ resolver: zodResolver(resetPasswordSchema), defaultValues: { password: '', confirmPassword: '' } }); return <View style={styles.authContent}><Brand /><Text style={[typography.screenTitle, { color: theme.textPrimary }]}>Choose a new password</Text><View style={styles.form}><Controller control={control} name="password" render={({ field }) => <Field label="New password" secureTextEntry value={field.value} onChangeText={field.onChange} error={errors.password?.message} />} /><Controller control={control} name="confirmPassword" render={({ field }) => <Field label="Confirm password" secureTextEntry value={field.value} onChangeText={field.onChange} error={errors.confirmPassword?.message} />} />{error && <ErrorNotice message={error} />}<PrimaryButton title={busy ? 'Updating…' : 'Update password'} onPress={handleSubmit(({ password }) => resetPassword(password))} disabled={busy} /></View></View>; }

function ErrorNotice({ message }: { message: string }) { const theme = useTheme(); return <View style={[styles.error, { backgroundColor: theme.dangerMuted }]}><Ionicons name="alert-circle-outline" size={18} color={theme.danger} /><Text style={[typography.bodyMedium, { color: theme.danger, flex: 1 }]}>{message}</Text></View>; }
function FooterPrompt({ copy, action, onPress }: { copy: string; action: string; onPress: () => void }) { const theme = useTheme(); return <View style={styles.footerPrompt}><Text style={[typography.bodyMedium, { color: theme.textSecondary }]}>{copy}</Text><Pressable onPress={onPress}><Text style={[typography.bodyMedium, { color: theme.primary }]}>{action}</Text></Pressable></View>; }

const styles = StyleSheet.create({
  welcome: { flex: 1, paddingHorizontal: spacing.xl, paddingTop: spacing.xxl, paddingBottom: spacing.xxl, justifyContent: 'space-between', gap: spacing.xl }, brand: { flexDirection: 'row', alignItems: 'center', gap: spacing.xs }, brandMark: { width: 34, height: 34, borderRadius: 11, justifyContent: 'center', paddingHorizontal: 8, gap: 3 }, brandLine: { height: 2, width: 18, borderRadius: 2, backgroundColor: '#fff' }, brandName: { fontSize: 20, fontWeight: '700', letterSpacing: -0.5 },
  heroVisual: { height: 235, borderRadius: radius.xl, borderWidth: 1, padding: spacing.md, overflow: 'hidden' }, heroTop: { height: 92, margin: -spacing.md, padding: spacing.lg, flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, heroPill: { width: 36, height: 36, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, heroNumber: { fontSize: 26, fontWeight: '700', marginTop: 2 }, heroBars: { height: 105, flexDirection: 'row', alignItems: 'flex-end', gap: 9, paddingHorizontal: spacing.sm, paddingTop: spacing.md }, heroBar: { flex: 1, borderTopLeftRadius: 6, borderTopRightRadius: 6 }, floatingCard: { position: 'absolute', bottom: 12, left: 32, right: 16, height: 64, borderRadius: radius.md, borderWidth: 1, flexDirection: 'row', alignItems: 'center', padding: spacing.sm, gap: spacing.sm, shadowColor: '#000', shadowOpacity: 0.1, shadowRadius: 14, shadowOffset: { width: 0, height: 7 }, elevation: 6 }, floatingIcon: { width: 38, height: 38, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  secondaryButton: { minHeight: 50, borderRadius: radius.md, borderWidth: 1, alignItems: 'center', justifyContent: 'center' }, demoButton: { minHeight: 40, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6 },
  authContent: { flexGrow: 1, padding: spacing.xl, paddingTop: spacing.xxl, gap: spacing.xxl }, back: { width: 44, height: 44, borderRadius: 14, borderWidth: 1, alignItems: 'center', justifyContent: 'center' }, form: { gap: spacing.lg }, nameRow: { flexDirection: 'row', gap: spacing.sm }, footerPrompt: { flexDirection: 'row', justifyContent: 'center', gap: 5 }, error: { minHeight: 48, borderRadius: radius.md, padding: spacing.sm, flexDirection: 'row', alignItems: 'center', gap: spacing.xs }, sentIcon: { width: 72, height: 72, borderRadius: 24, alignSelf: 'center', alignItems: 'center', justifyContent: 'center' },
  centered: { flex: 1, padding: spacing.xl, alignItems: 'center', justifyContent: 'center', gap: spacing.lg }, largeIcon: { width: 78, height: 78, borderRadius: 26, alignItems: 'center', justifyContent: 'center' },
});
